943 initFunction and initArgs logic is wrong
near/near-cli pull request #944
Opened 2022-02-24 19:37 UTC by willemneal

Use "new" if `--initArgs` is provided but `--initFunction` is not.

2022-02-26 19:42 UTC, nearmax requested changes
The entire logic can be fixed by setting `default` of `initFunction` to `"new"`.

2022-03-15 11:09 UTC, volovyk-s approved these changes

2022-03-15 11:09 UTC, merged

2022-04-24 07:14 UTC, kalloc commented
Hi, but what about contract re-deploy/upgrade? Is I understand that  initFunction for migration not always required.

2022-04-25 09:46 UTC, volovyk-s commented
@kalloc yes, `new` as default caused some bugs. Addressed in https://github.com/near/near-cli/pull/969